### ISSUE TITLE
Rete js

### ISSUE THREAD

**Issue by michaelsharpe** [Ni55aN/easyhard.js#28]
Hello!

I noticed you are still super active on GitHub and on this project, but Rete seems to be abandoned.  Is it still supported?  It would be good to announce on it if you are no longer maintaining, answering questions and fixing bugs for people. Maybe look to find some to core contributors to help you out?

It is a great project.  I have been using it heavily and made some major changes to a few plugins (such as modifying the module plugin to support passing in task actions, as well as passing them out).

I have a number of questions, such as what a good strategy would be for unit testing both components as well as custom plugins.  However you have been very inactive and I would love to get some time from you at some point for some support.  If it were being more actively worked on, I would even looking into my company helping via Patreon support, or financial support.

**Comment by Ni55aN** [comment]
Hello, @michaelsharpe

Rete.js is still supported. As far as I can see, the issues don't have any critical bugs that would need to be fixed. All the rest are minor flaws that can be solved by writing custom plugins

As for the answers to the questions: indeed, I rarely answer the questions (or reviewing PRs). I have other priorities at the moment (as you noticed from this repository). On the other hand, users can get the answers to their questions in the documentation (of course, it is not perfect), and by reading the source code

In general, as for the current stage of development of Rete.js, I hope it fully covers the needs of other projects (within reason). I also have ideas for its radical improvements with breaking changes, but not in the near future

**Comment by michaelsharpe** [comment]
@Ni55aN Thanks for the response!  And that makes sense.

Any way I could get some of your time to help me understand a possible strategy for testing both components and custom plugins?  What I am building needs a high level of stability and I am having a hard time figuring out how I might go about this.

**Comment by Ni55aN** [comment]
> Any way I could get some of your time to help me understand a possible strategy for testing both components and custom plugins?

I can help with this since for Rete.js I do not declare any testing strategies other than those described on the Internet. 
I believe that you should focus on E2E testing in order to have more guarantees about the stability from the user's point of view.
